name: Publish to npm

on: workflow_dispatch

#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
        
    - name: Publish
      uses: borales/actions-yarn@v4
      with:
        cmd: pack --dry-run
